version: '3.8'

services:
  postgres:
    image: postgres:16.4-alpine
    container_name: ew-postgres
    restart: unless-stopped 
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    container_name: ew-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  adminer:
    image: adminer
    container_name: ew-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  mongo-express:
    image: mongo-express
    container_name: ew-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

volumes:
  postgres_data:
  mongo_data:
