DROP TABLE IF EXISTS TB_HEROIS;

CREATE TABLE TB_HEROIS (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NOME TEXT NOT NULL,
  PODER TEXT NOT NULL
)

--CREATE
INSERT INTO TB_HEROIS (NOME, PODER) 
VALUES 
  ('Flash', 'Velocidade'),
  ('Aquaman', 'Nadar'),
  ('Batman', 'Dinheiro')

--READ
SELECT * FROM TB_HEROIS;
SELECT nome FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE nome = 'Batman';

--UPDATE
UPDATE TB_HEROIS
SET nome = 'Flash Reverso'
WHERE id = 1;

--DELETE
DELETE FROM TB_HEROIS WHERE id = 1;